import { v4 as uuid } from "uuid";
// import {Annic} from "../images/annivc.jpg"

export const products = [
  {
    _id: uuid(),
    title: "Anniversary Cake",
    // image:Annic,
    price: "2000",
    categoryName: "Celebration Cakes",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Birthday Cake",
    // image:Annic,
    price: "2500",
    categoryName: "Celebration Cakes",
    rating: "3.8",
  },
  {
    _id: uuid(),
    title: "BabyShower Cake",
    // image:Annic,
    price: "1000",
    categoryName: "Celebration Cakes",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Christmas Cake",
    // image:Annic,
    price: "1500",
    categoryName: "Celebration Cakes",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Pearl Wedding Cake",
    // image:Annic,
    price: "1300",
    categoryName: "Wedding Cakes",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Flower Wedding Cake",
    // image:Annic,
    price: "4000",
    categoryName: "Wedding Cakes",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Golden Wedding Cake",
    // image:Annic,
    price: "2300",
    categoryName: "Wedding Cakes",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Classic Wedding Cake",
    // image:Annic,
    price: "6000",
    categoryName: "Wedding Cakes",
    rating: "5",
  },
  {
    _id: uuid(),
    title: "Medical Graduation Cake",
    // image:Annic,
    price: "2300",
    categoryName: "Graduation Cakes",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Engineering Graduation Cake",
    // image:Annic,
    price: "3000",
    categoryName: "Graduation Cakes",
    rating: "3.5",
  },
  {
    _id: uuid(),
    title: "School Graduation Cake",
    // image:Annic,
    price: "1900",
    categoryName: "Graduation Cakes",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "College Graduation Cake",
    // image:Annic,
    price: "2000",
    categoryName: "Graduation Cakes",
    rating: "2.5",
  },
];
