import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    title: "Anniversary Cake",
    image:"https://i.pinimg.com/originals/24/4b/f2/244bf2437c7739a32600babe157d8ad8.jpg",
    price: "2000",
    categoryName: "Celebration Cakes",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Birthday Cake",
    image:"https://www.itakeyou.co.uk/wp-content/uploads/2021/08/first-birthday-cakes-1.jpg",
    price: "2500",
    categoryName: "Celebration Cakes",
    rating: "3.8",
  },
  {
    _id: uuid(),
    title: "BabyShower Cake",
    image:"https://www.cakedeliveryinbareilly.in/wp-content/uploads/2021/01/Baby-Shower-Cake.jpg",
    price: "1000",
    categoryName: "Celebration Cakes",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Christmas Cake",
    image:"https://yummycake.in/wp-content/uploads/2022/12/santa-claus-cake.png",
    price: "1500",
    categoryName: "Celebration Cakes",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Pearl Wedding Cake",
    image:"https://www.elegantweddinginvites.com/wedding-blog/wp-content/uploads/2015/12/traditional-white-wedding-cake-buttercream-and-pearl-details.jpg?weddmobile?bl20",
    price: "1300",
    categoryName: "Wedding Cakes",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Flower Wedding Cake",
    image:"https://i.pinimg.com/originals/c2/ab/f1/c2abf15d08be39d07e37b0c42903de29.png",
    price: "4000",
    categoryName: "Wedding Cakes",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Golden Wedding Cake",
    image:"https://www.melsamazingcakes.com/wp-content/uploads/2019/07/662E8D19-6F52-4676-8190-CC0F97DE3656.jpeg",
    price: "2300",
    categoryName: "Wedding Cakes",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Classic Wedding Cake",
    image:"https://media2.insideweddings.com/images/0093-93-keri-93-93.original.jpg",
    price: "6000",
    categoryName: "Wedding Cakes",
    rating: "5",
  },
  {
    _id: uuid(),
    title: "Medical Graduation Cake",
    image:"https://pbs.twimg.com/media/Da9_s1wXcAE2Gfp.jpg",
    price: "2300",
    categoryName: "Graduation Cakes",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Engineering Graduation Cake",
    image:"https://cdn.shopify.com/s/files/1/0034/8343/5072/products/WhatsAppImage2021-01-05at1.16.28PM.jpg?v=1610805508",
    price: "3000",
    categoryName: "Graduation Cakes",
    rating: "3.5",
  },
  {
    _id: uuid(),
    title: "School Graduation Cake",
    image:"https://i.pinimg.com/originals/d2/2d/1a/d22d1acb7af7b7f8a88bfab2bbe1c9db.jpg",
    price: "1900",
    categoryName: "Graduation Cakes",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "College Graduation Cake",
    image:"https://www.classygirlcupcakes.com/wp-content/uploads/2015/01/graduation-logo-tiered-cake-shorewood-high-school-web.jpg",
    price: "2000",
    categoryName: "Graduation Cakes",
    rating: "2.5",
  },
];
